[package]
name = "youtube_downloader"
version = "0.1.0"
authors = ["L-oris <loris4526@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
dialoguer = "0.7"
futures = "0.3"
smol = "1"
